### ISSUE TITLE
Improve `eq` method 

### ISSUE THREAD

**Issue by Kelin2025** [Kelin2025/nanoutils#1]
- [x] Deep equality check
- [x] RegExp and Date objects check
- [x] ES 6 Maps/Sets check
- [ ] Solve circular objects

**Comment by Kelin2025** [comment]
So, circular objects are OK, but here is one case in it doesn't work:
The following one works correctly:
```javascript
var a = { a: 1, b: 2, c: 3 }
var b = { a: 1, b: 2, c: 3 }
a.d = a
b.d = a
eq(a, b) // true
```
But this one not:
```javascript
var a = { a: 1, b: 2, c: 3 }
var b = { a: 1, b: 2, c: 3 }
a.d = a
b.d = b
eq(a, b) // false
```
Working on that problem

**Comment by Beraliv** [comment]
The discussion will be continued in https://github.com/nanoutils/nanoutils/issues/180
