### ISSUE TITLE
Add 'concat', 'fill', 'join' lodash methods

### ISSUE THREAD

**Issue by BabkinAleksandr** [Kelin2025/nanoutils#12]
Add 
- [concat](https://lodash.com/docs/4.17.4#concat)
- [fill](https://lodash.com/docs/4.17.4#fill)
- [join](https://lodash.com/docs/4.17.4#join)

lodash methods

If is all OK, please just make me assignee of this task.

_P.S. Is it acceptible workflow (task - task review - task assignee)?_

**Comment by Kelin2025** [comment]
You can add methods without issues. I create methods with names similar to Ramda equivalents
See https://ramdajs.com/docs when you aren't sure if method exists
