### ISSUE TITLE
Ramda naming

### ISSUE THREAD

**Issue by Beraliv** [Kelin2025/nanoutils#15]
I will leave this file to replace existing methods to be renamed according to Ramda naming

- [x] `a2p`
- [x] `applyTo`
- [x] `ary` (https://github.com/Kelin2025/nanoutils/commit/fcfb8c3107c7e922d3234e506080f2c74819c887)
- [x] `ascend`
- [ ] `compact`
- [x] `debounce`
- [x] `descend`
- [x] `dropRight` would be `dropLast` (https://github.com/Kelin2025/nanoutils/pull/17)
- [x] `dropRightWhile` would be `dropLastWhile` (https://github.com/Kelin2025/nanoutils/pull/17)
- [x] `eq` would be `equals` (https://github.com/Kelin2025/nanoutils/pull/17)
- [ ] `eqLens`
- [x] `eqWith`
- [x] `first` (https://github.com/Kelin2025/nanoutils/commit/fcfb8c3107c7e922d3234e506080f2c74819c887)
- [x] `flatten` would be `unnest` (https://github.com/Kelin2025/nanoutils/pull/17)
- [x] `flattenDepth` would be `flatten` (https://github.com/Kelin2025/nanoutils/pull/17)
- [x] `flattenDepth` (would suggest `unnestN`) (https://github.com/Kelin2025/nanoutils/pull/17)
- [x] `flattenObj`
- [x] `get` would be `prop` (https://github.com/Kelin2025/nanoutils/commit/0e968717197b9f90594146be038e519328fe6ba4)
- [x] `getLens` would be `view` (https://github.com/Kelin2025/nanoutils/commit/0e968717197b9f90594146be038e519328fe6ba4)
- [x] `isInteger`
- [x] `noop`
- [x] `omitBy`
- [x] `p2a`
- [x] `placehold`
- [x] `set` would be `assoc` (https://github.com/Kelin2025/nanoutils/commit/0e968717197b9f90594146be038e519328fe6ba4)
- [x] `setLens` would be `set` (https://github.com/Kelin2025/nanoutils/commit/0e968717197b9f90594146be038e519328fe6ba4)
- [x] `takeRight` would be `takeLast` (https://github.com/Kelin2025/nanoutils/pull/17)
- [x] `takeRightWhile` would be `takeLastWhile` (https://github.com/Kelin2025/nanoutils/pull/17)
- [x] `throttle`
- [x] `toArray`
- [x] `unzip`
- [x] `unzipWith`
- [ ] `update` would be over (https://github.com/Kelin2025/nanoutils/commit/0e968717197b9f90594146be038e519328fe6ba4)
- [ ] `updateLens`
- [ ] `zipObject` would be `zipObj` (?)
- [x] `zipObjectDeep`

**Comment by Kelin2025** [comment]
Fixed some names, also fixed tests. Check this:
https://github.com/Kelin2025/nanoutils/pull/17

**Comment by Kelin2025** [comment]
## :white_check_mark:  Correct names
applyTo
ascend
descend

## :warning:  Incorrect names
ary -> nAry
first -> head

## :warning: Incorrect work according to compability with Ramda
get -> prop
getLens -> view
set -> assoc
setLens -> set
update -> over
updateLens -> ?

## :no_entry_sign:  Not from Ramda
a2p
debounce
eqWith
flattenObj
isInteger
noop
omitBy (interesting, why)
placehold
p2a
toArray
throttle
unzip
unzipWith
zipObjectDeep

## :question: Unknown
compact

**Comment by Beraliv** [comment]
Incorrect work according to compability with Ramda
- [x] fixed
- [ ] need to make up a name for `updateLens`

**Comment by Kelin2025** [comment]
`updateLens` is like `over`, isn't it?  
Ramda hasn't just `update` method
