### ISSUE TITLE
Add 'chunk' method

### ISSUE THREAD

**Issue by BabkinAleksandr** [Kelin2025/nanoutils#2]
Hello, I'm inspired by your project, because of facing the same bundle-size issues.
I would like to make contributions and begin with [lodash chunk method](https://lodash.com/docs/4.17.4#chunk) (because it's the first in the list and I don't see it in current project).

This task is just to be sure no one is working on the same method and to practice for participating in this project. Will my help be useful and could I begin?

So, I will looking forward your answer and accepting my help.

**Comment by Kelin2025** [comment]
Hello!
Yes, of course, you can :)
One important note - methods should follow the next principles
- 1KB limit 
- iteratee-first data-last
- if method has 2+ arguments, it should be curried (just wrap it in `curry` method)
I'll add you to contributors when I'll come home
Good luck!

**Comment by Kelin2025** [comment]
Oh, wait
`lodash.chunk` is equal wtih `ramda.aperture` that's already in `nanoutils`
