### ISSUE TITLE
Internal methods

### ISSUE THREAD

**Issue by Kelin2025** [Kelin2025/nanoutils#22]
I think we need to add _internal_ methods to use inside main methods.  
Idea is to move repeated parts (like Object.keys + reduce, adding read-only nanoLen property etc) out and use 'em over the library.  
It may add some bytes, but total library size will be much smaller.

**Comment by Beraliv** [comment]
Good idea, even more helper library for small library

**Comment by Kelin2025** [comment]
See there: https://github.com/Kelin2025/nanoutils/pull/23
