### ISSUE TITLE
debounce

### ISSUE THREAD

**Issue by shrpne** [Kelin2025/nanoutils#33]
`debounce` function should reset timeout https://davidwalsh.name/javascript-debounce-function

For now, it does not reset and works as `throttle`, the only difference `throttle` run function before the timer, `debounce` run function after the timer.

**Comment by Kelin2025** [comment]
Hi!  
Thanks for the issue, I'll fix it in a few days (have some another work)

**Comment by Kelin2025** [comment]
I made a PR, I will be grateful if you will check it: https://github.com/nanoutils/nanoutils/pull/2  
P.S. We moved repo to organization
