### ISSUE TITLE
Fix types

### ISSUE THREAD

**Issue by Kelin2025** [Kelin2025/nanoutils#4]
@Beraliv there's one moment with types.
For example, this one is incorrect: 
https://github.com/Kelin2025/nanoutils/commit/90e7808792d3d4e00212b8ffbb201c78e4643d89#diff-5b8f70683265ca109e30c5871e2151e7
Because divide method is **curried** and `divide(5)` returns a function.
We should take this moment

**Comment by Beraliv** [comment]
@Kelin2025 Oh, yeah. Need to think through it.
As I understand, it concerns a lot of files now.

**Comment by Beraliv** [comment]
I think this Gist is helping for our case
https://gist.github.com/donnut/fd56232da58d25ceecf1

**Comment by Beraliv** [comment]
Will continue in https://github.com/nanoutils/nanoutils/issues/159
