### ISSUE TITLE
Search optimisation

### ISSUE THREAD

**Issue by Beraliv** [Kelin2025/nanoutils#41]
`Set` is useful to prevent `arr.some(predicate)` as it requires linear complexity and can be `O(n^2)` in the worst case.

Need to discuss and think through it.

It was initiated after [PR #40](https://github.com/Kelin2025/nanoutils/pull/40)
Also connected to [PR #41](https://github.com/Kelin2025/nanoutils/issues/41)

**Comment by Kelin2025** [comment]
Will we drop old platforms support?

**Comment by Beraliv** [comment]
We shouldn't

**Comment by Kelin2025** [comment]
But `Sets` are es6

**Comment by Beraliv** [comment]
Yeah, I mean set-like, maybe object with getHashCode?

**Comment by Beraliv** [comment]
`indexOf` is faster
