### ISSUE TITLE
To add sizes of files and total size to SIZES.md file

### ISSUE THREAD

**Issue by Beraliv** [Kelin2025/nanoutils#8]
As the aim of the library is to reduce its size, I would suggest a board ideally or just a file to follow sizes of files and update it before ```git push``` or ```git commit``` using git hooks.

The only one issue here is how to save info to the file.

**Comment by Kelin2025** [comment]
Done!  
See [SIZES.md](https://github.com/Kelin2025/nanoutils/blob/master/SIZES.md)

**Comment by Kelin2025** [comment]
[**SIZES.md**](https://github.com/Kelin2025/nanoutils/blob/master/SIZES.md) is done  
Git hooks'll come a little later ;)

**Comment by Beraliv** [comment]
Do we need to update it manually?

**Comment by Kelin2025** [comment]
I thought about that. Here is one problem:  
If I add it to precommit hook, it will update even if none of methods has changed (e.g. you add some tests, but it will recalculate size)  
I can write custom util for commits, but it looks dumb.

**Comment by Beraliv** [comment]
`prepush` can be enough, no?

**Comment by Kelin2025** [comment]
It looks OK, but it makes `SIZES.md` for each commit even if methods aren't changed (then it also throws error)  
To fix _error_, I added timestamp, but I think its' ugly to make `SIZES.md` for each push
